version: '3.8'

services:
  backend:
    build:
      context: ./
    container_name: cpms_api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.7.2
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0924
      MYSQL_DATABASE: cpms_prod
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
